name: ROS2
on: [push, pull_request]

jobs:
  build-and-test:
    name: Building ROS2 project
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install ROS2 humble
        shell: bash
        run: |
          sudo ./scripts/ros2/install.sh
          ./scripts/ros2/post-install.sh

      - name: Install ethercat_grant
        shell: bash
        run: ./scripts/ethercat_grant/install.sh

      - name: Build using script
        shell: bash
        run: ./scripts/build-ros.sh -n
