name: ROS2
on: [push, pull_request]

jobs:
  build-and-test:
    name: Building ROS2 project
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install ROS2 humble
        shell: bash
        run: |
          sudo ./scripts/ros2/install.sh
          ./scripts/ros2/post-install.sh

      - name: Build library - SOEM
        shell: bash
        run: sudo ./scripts/soem/install.sh

      - name: Build project
        shell: bash
        run: |
          source /home/$USER/.bashrc
          source /opt/ros/humble/setup.bash
          cd ./ros2
          colcon build --symlink-install --cmake-args -DSECURITY=ON -DBUILD_TESTING=ON

      - name: Run project tests
        shell: bash
        run: |
          cd ./ros2
          source ./install/setup.bash
          colcon test
          colcon test-result --all --verbose

      - name: Build using script
        shell: bash
        run: ./scripts/build-ros.sh
