name: Compiling and testing ROS2
on: [push]

jobs:
  build-and-test:
    name: Building ROS2 project
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
