name: Compiling and testing ROS2
on: [push]

jobs:
  build-and-test:
    name: Building ROS2 project
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install
        run: sudo ./scripts/ros2/install.sh

      - name: Post install
        run: ./scripts/ros2/post-install.sh

      - name: Build
        run: |
          source /home/$USER/.bashrc
          source /opt/ros/humble/setup.bash
          cd ./ros2
          colcon build --symlink-install --cmake-args -DSECURITY=ON -DBUILD_TESTING=ON

      - name: Run test
        run: |
          source ./install/setup.bash
          cd ./ros2
          colcon test
